version: '3'

services:

  frontend:
    container_name: "frontend"
    build:
      context: ./src/Front
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src/Front/node_modules:/var/app/front/node_modules
      - ./src/Front:/var/app/front

  backend:
    container_name: "backend"
    build:
      context: ./src/Back
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
    env_file:
      - "./src/Back/.env"
    environment:
      DATABASE_URL: "postgres://postgres:api@database:5432/nodeCrud"
    volumes:
      - "./src/Back/node_modules:/var/app/back/node_modules"
      - "./src/Back:/var/app/back"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    restart: always
    ports:
      - "8081:8081"

  database:
    container_name: "database1"
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - "database-data:/var/lib/postgres"
    environment:
      POSTGRES_DATABASE: "nodeCrud"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "api"

volumes:
  database-data: {}
