version: '3'

services:

  frontend:
    container_name: "frontend"
    build:
      context: ./src/Front
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /:/node_modules
      - ./:/app

  backend:
    container_name: "backend"
    build:
      context: ./src/Back
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: always
    env_file:
      - .env
    environment:
      DATABASE_URL: mysqlx://root:crud1234@database:3306/nodeCrud
    volumes:
      - /:/node_modules
      - ./:/app

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    restart: always
    ports:
      - "80:80"

  database:
    container_name: "data_crudApp"
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "crud1234"
      MYSQL_DATABASE: "nodeCrud"
      MYSQL_USER: "nodecrud"
      MYSQL_PASSWORD: "crud1234"

volumes:
  dbdata: {}
