version: '2'

services:

  frontend:
    container_name: "frontend"
    build:
      context: ./src/Front
      dockerfile: Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./src/Front/node_modules:/var/app/front/node_modules
      - ./src/Front:/var/app/front

  backend:
    container_name: "backend"
    build:
      context: ./src/Back
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
    env_file:
      - ./src/Back/.env
    environment:
      DATABASE_URL: mysqlx://root:api@database:3306/nodecrud
    volumes:
      - "./src/Back/node_modules:/var/app/back/node_modules"
      - "./src/Back:/var/app/back"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    restart: always
    ports:
      - "8081:8081"

  database:
    container_name: "mysql"
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: api
      MYSQL_DATABASE: nodecrud

volumes:
  db_data: {}
