version: '3'

services:

  backend:
    container_name: "backend"
    build:
      context: ./src/Back
      dockerfile: Dockerfile
    depends_on:
      - database
    links:
      - database
    env_file:
      - ./src/Back/.env
    environment:
      DATABASE_URL: "postgres://postgres:api@database:5432/nodeCrud"
    volumes:
      - ./src/Back/node_modules:/var/app/back/node_modules
      - ./src/Back:/var/app/back

  database:
    container_name: "database"
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgres
    environment:
      POSTGRES_DATABASE: nodeCrud
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: api

volumes:
  dbdata: {}
