version: '3'

services:

  frontend:
    container_name: "front"
    build:
      context: ./src/Front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./front:/src/

  backend:
    container_name: "back"
    build:
      context: ./src/Back
      dockerfile: Dockerfile
    env_file:
      - .env
    links:
      - database
    environment:
        DATABASE_URL: mysqlx://root:crud1234@back:3306/nodeCrud
    volumes:
      - ./back:/src/

  database:
    container_name: "data_crudApp"
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "crud1234"
      MYSQL_DATABASE: "nodeCrud"
      MYSQL_USER: "nodecrud"
      MYSQL_PASSWORD: "crud1234"

volumes:
  dbdata: {}
